[VFS/STFS] Use xe::filesystem::OpenFile instead of MappedMemory, other small improvements
xenia-project/xenia pull request #1807
Opened 2021-05-15 12:08 UTC by emoose

Changes StfsContainerDevice to use `xe::filesystem::OpenFile` / `FILE*` instead of MappedMemory, maybe can help with nested packages (guess we might need to go a little further & add support for loading from vfs::Entry or something for that though?)

There's a few other minor improvements that the commit msgs go into, adding names to some anonymous structs, making the vfs::Device functions like `available_allocation_units()` return something more useful, etc.

Moved the x360-specific structs to stfs_xbox.h so they aren't filling stfs_container_device.h any more, should make it more obvious these are structs X360 itself uses too, not something that we defined.

---

Like my previous STFS PR I haven't been able to test with that many packages, the ones I've tried didn't seem to have any issues, but if anyone is able to test with more packages/SVODs it'd be appreciated.

(also I wonder if changing MappedMemory out for OpenFile might affect load times at all? Didn't notice anything myself, but I didn't really look into it much)

---

I made these changes while working on adding support for writing out packages to StfsContainerDevice, more info about that here: https://github.com/xenia-project/xenia/pull/1793#issuecomment-837699003 / https://github.com/emoose/xenia/commits/stfs-writer

Might be a while before I have that ready though so figured this might be worth PRing seperately, but if anyone has any thoughts about that STFS writing code I'd be happy to hear them!

2021-05-15 12:14 UTC, gibbed commented
Are we losing any significant performance benefit by moving to typical file reads?

2021-05-15 12:25 UTC, gibbed requested changes

2021-05-15 12:25 UTC, gibbed commented on src/xenia/vfs/devices/stfs_container_device.cc
> +  uint32_t root_block;
Perhaps a locally defined struct to read into, as opposed to a batch set of variables?

2021-05-15 12:25 UTC, gibbed commented on src/xenia/vfs/devices/stfs_container_device.cc
> +  fread(&header_, sizeof(StfsHeader), 1, header_file);
`fread`s (not just this one) could probably use return value checking to ensure the count matches what we expect.

2021-05-15 12:25 UTC, gibbed commented on src/xenia/vfs/devices/stfs_container_device.cc
> +  uint16_t node_l;
Perhaps a locally defined struct to read into, as opposed to a batch set of variables?

2021-05-16 15:41 UTC, emoose commented
Will update with requested changes soon, need to test with some packages from my box first.

BTW does anyone know if `#pragma pack(push, 1)` is available on GCC/Clang, and would that be better than using `XEPACKEDSTRUCT`?

Googling around shows they apparently should support it, but I don't know if that's something that has to be specially enabled or something. I'm assuming there's a reason we have `XEPACKEDSTRUCT` instead of using pragma?

2021-05-16 18:05 UTC, JoelLinn commented
> BTW does anyone know if `#pragma pack(push, 1)` is available on GCC/Clang, and would that be better than using `XEPACKEDSTRUCT`? Seems VS has some Intellisense issues with `XEPACKEDSTRUCT`, and sounds like it might be breaking GCC pretty badly too...

Very good point, I actually didn't know that existed. I have been working on (re-)introducing GCC compatibility (#1797) but gcc doesn't like the packed attribute when non POD types are involved (was able to fix some but your last PR basically made gcc unfixable because of that)
Looks like the `#pragma pack(push, 1)` is indeed [supported by all three compilers ](https://godbolt.org/z/bfoazq3dE) and for some reason GCC now works better.

@gibbed  I think we might just as well phase out our macros(?)

Didn't check yet if that also fixes the issues with GCC for `unions` but it's at least something

2021-05-17 22:28 UTC, emoose commented
Updated with req'd changes, also fixed some parts to use references instead of copying (`auto file = files_.at(0)` -> `auto& file`), and swapped out `XEPACKEDSTRUCT`s for `#pragma pack` instead.

Hopefully might help with the issues GCC was having, but I think the `be<uint16_t>`/`char16_t` unions could still have problems there, in my stfs-writer branch I noticed sometimes those unions would stop copy-constructor being generated for some reason, maybe something similar is happening there too?

2021-05-17 23:45 UTC, gibbed commented
@JoelLinn Instead of phasing out the macro, wouldn't it be wiser to flip it to doing what GCC can support?

(this wouldn't be an expected change for this PR)

2021-05-17 23:52 UTC, gibbed requested changes

2021-05-17 23:52 UTC, gibbed commented on src/xenia/vfs/devices/stfs_container_device.cc
> +    uint32_t root_block;
Naming. Why retain `root_` prefix here within the structure?

2021-05-17 23:52 UTC, gibbed commented on src/xenia/vfs/devices/stfs_container_device.cc
> +    auto& fragment = fragment_files.at(i);
Unless I'm mistaken, `const`-ness is possible here?

2021-05-17 23:52 UTC, gibbed commented on src/xenia/vfs/devices/stfs_container_device.cc
> +      if (memcmp(magic_buf, XSF_MAGIC, 3) == 0) {
`std::` prefix.

2021-05-17 23:52 UTC, gibbed commented on src/xenia/vfs/devices/stfs_container_device.cc
> +    if (memcmp(magic_buf, MEDIA_MAGIC, 20) == 0) {
`std::` prefix.

2021-05-17 23:52 UTC, gibbed commented on src/xenia/vfs/devices/stfs_container_device.cc
> +      if (memcmp(magic_buf, MEDIA_MAGIC, 20) == 0) {
`std::` prefix.

2021-05-17 23:52 UTC, gibbed commented on src/xenia/vfs/devices/stfs_container_device.cc
> +    if (memcmp(magic_buf, MEDIA_MAGIC, 20) == 0) {
`std::` prefix.

2021-05-18 08:28 UTC, JoelLinn commented
> @JoelLinn Instead of phasing out the macro, wouldn't it be wiser to flip it to doing what GCC can support?
> 
> (this wouldn't be an expected change for this PR)

I thought we couldn't use `#pragma` in the macro.
I was today years old when I learned that `_Pragma("...")` is available with GCC/Clang similar to MSVCs `__pragma( .... )`
I will address this in the GCC PR. 
Note that `#pragma pack()` is already used a number of times in master right now

2021-05-18 12:47 UTC, emoose commented
Updated with requested changes

2021-05-18 14:04 UTC, gibbed approved these changes

2021-05-18 14:04 UTC, merged