[XAM] Implemented: XStaticContentEnumerator
xenia-project/xenia pull request #1812
Opened 2021-05-18 08:20 UTC by Gliniak

Based on Rick's ``AchievementEnumerator``.

I had to split ``ContentEnumerator`` into separate entity because: 
1. It will allow to implement custom logic for that specific enumerator
2. Sometimes games instead of providing _buffer_size_ in bytes they provide some arbitrary value (probably max amount of files).

I probably forgot about something or something can be simplified, so please point that out. Thanks

Affected games:
- Splatterhouse
- ¯\_(ツ)_/¯ (We will see soon)

2021-05-18 22:41 UTC, gibbed requested changes

2021-05-18 22:41 UTC, gibbed commented on src/xenia/kernel/xam/xam_enum.cc
> -    result = X_ERROR_INSUFFICIENT_BUFFER;
You've removed this check, which I would prefer to keep.

2021-05-18 22:41 UTC, gibbed commented on src/xenia/kernel/xam/xam_content.cc
> +      details[i].content_type = item.content_type;
The `ContentData` type already has a helper function for (correctly) writing out to guest memory. You don't need to do it yourself here.

```cpp
item.Write(&details[i]);
```

2021-05-18 22:41 UTC, gibbed commented on src/xenia/kernel/xam/xam_enum.cc
> -      //   Final Fight: Double Impact (saves)
Are saves "content" here that your enumerator would correct Final Fight's behavior? I don't recall.

2021-05-19 06:13 UTC, Gliniak commented
Thanks for the review. 
I see you have that "problematic" game. Would you mind to check if saving works correctly.

2021-05-19 06:14 UTC, Gliniak commented on src/xenia/kernel/xam/xam_content.cc
> +      actual_buffer_size = items_size * items_per_enumerate();
I'm not exactly sure if that logic is correct here. In terms of savefiles probably, but I don't know how it will behave with other content types

2021-06-30 08:42 UTC, Gliniak commented
Superseded by #1862 
I will check if my test case works with new version

2021-06-30 08:42 UTC, closed without merging