Rebindable keyboard controls
xenia-project/xenia pull request #1891
Opened 2021-09-20 22:22 UTC by epozzobon

This pull request makes it possible to rebind the keyboard controls in the xenia config file. This fixes #1333.
It supports switching layers using caps lock (as the current default key bindings) and multiple keys for the same gamepad input.

I acknowledge that the syntax is a bit awkward, and I would be happy to get some feedback on how I can improve it while maintaining compatibility with xenia's current key bindings.

As it stands, the syntax works like this:
`keybind_a = "0xBA"`      # binds key code 0xBA to the A button
`keybind_b = "'X'" `     # binds the X key to the B button. Chars are indicated by `'` as per C convention.
`keybind_a = "0xBA"`      # binds key code 0xBA to the A button
`keybind_right_trigger = "'E' 'O'"`      # binds both keys E and O to the right trigger. Space is used as a separator.

Bind the S key to dpad down when caps lock or shift are enabled, and to left thumb down otherwise:
```
keybind_dpad_down = "^'S'" 
keybind_left_thumb_down = "_'S'"
```

2021-09-21 02:26 UTC, gibbed requested changes
In general, I like what you've done with the token stuff.

I don't really like the single quotes for character key definitions, but I haven't really thought of a better format yet. I'll think on it.

2021-09-21 02:26 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +        snprintf(buffer, 100, "KeyBind: token \"%s\" binds key 0x%x to controller input 0x%x", token, bind.key, controllerKey);
Don't use snprintf. `XELOGI` supports formatting. <https://fmt.dev/latest/index.html#format-api>

2021-09-21 02:26 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +        snprintf(buffer, 100, "KeyBind: failed to parse token \"%s\" for controller input 0x%x", token, controllerKey);
Don't use snprintf. `XELOGW` supports formatting. <https://fmt.dev/latest/index.html#format-api>

2021-09-21 02:26 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +  while (keyBindCVar[off] != 0) {
`std::string` is not obligated to be null terminated, this should be a length check.

2021-09-21 02:26 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +      if (s[0] == '\'' && s[1] != '\0') {
No verification that there is enough data left.

2021-09-21 02:26 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +    for (KeyBinding &b : key_bindings_)
`const Keybinding &b`

2021-09-21 02:26 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +        unsigned long ul = strtoul(s, &endptr, 0);
Don't use `strtoul`, we have helper functions for this in `base/string_util.h` (see `from_string`).

2021-09-21 02:26 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +      memcpy(token, keyBindCVar.c_str() + off, end - off);
This seems completely unnecessary to have a raw `char` buffer. A substring of `keyBindCVar` should end up producing a `std::string_view` anyway.

2021-09-21 02:26 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +void WinKeyInputDriver::ParseKeyBindingCVar(ui::VirtualKey controllerKey, std::string keyBindCVar) {
`ParseKeyBindingCVar` seems a bit misrepresentative. You take in the value of the cvar here, so it's not really parsing a cvar, it's just parsing a key binding string which came from a cvar.

`ParseKeyBinding` would be a better name.

2021-09-21 02:30 UTC, gibbed commented
Additionally, I will look at implementing support for TOML arrays in our config reader/writer so we can have that without having a custom thing just for keybinds.

2021-09-22 00:41 UTC, epozzobon commented
All the issues you pointed out should now be fixed.
I also thought about a better syntax for the bindings: single quotations could be removed entirely, and instead all bindings are considered ascii by default except when they start with 0x.

I think it would make them look quite natural:
```
keybind_right_trigger = "E O"
keybind_a = "0xBA"
```

2021-09-22 01:05 UTC, epozzobon commented
(`xb format` makes a mess out of `DEFINE_string` statements so I'm not able to fix the continuous integration check.)

2021-09-22 18:54 UTC, gibbed commented
You can selectively toggle off and on clang-format.

Surround it with:

```// clang-format off```

```// clang-format on```

2021-09-23 00:21 UTC, epozzobon commented
I must be doing something wrong, but even with those lines, `xb format` tries to tab the entire namespace

2022-01-04 22:38 UTC, gibbed requested changes

2022-01-04 22:38 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +    end = std::min(end, bindVar.length());
I'd prefer end is properly checked if it's `std::string::npos`.

```cpp
if (end != std::string::npos) {
  end = std::min(end, bindVar.length());
} else {
  end = bindVar.length();
}
```

2022-01-04 22:38 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +    std::string token = bindVar.substr(off, end - off);
`token` can be a `std::string_view`, unless I'm mistaken.

2022-01-04 22:38 UTC, gibbed commented on src/xenia/hid/winkey/winkey_input_driver.cc
> +void WinKeyInputDriver::ParseKeyBinding(ui::VirtualKey controllerKey,
Please clean up your variable names according to [the style guide](https://google.github.io/styleguide/cppguide.html#Variable_Names).

2022-01-11 18:35 UTC, gibbed approved these changes

2022-01-11 18:38 UTC, merged