Update to new issue forms
xenia-project/xenia pull request #1921
Opened 2021-12-15 23:44 UTC by Margen67

Preview: https://github.com/Margen67/xenia/issues/new/choose

2022-01-04 11:20 UTC, Triang3l requested changes

2022-01-04 11:20 UTC, Triang3l commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      - label: This issue isn't specific to a game.
Issues in relatively obscure parts of the console often manifest themselves in very few games, and this checkbox may distract people from posting valid issues, I think. I'd keep this, but append something like "If the issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it."

2022-01-04 11:20 UTC, Triang3l commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      - label: The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
The period should be after "etc".

2022-01-04 11:20 UTC, Triang3l commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      - label: This issue isn't for tech support. (help with Xenia)
The period should be after the closing bracket.

2022-01-26 06:24 UTC, halotroop2288 approved these changes

2022-01-28 19:53 UTC, merged