Bump minimum Python to 3.7
xenia-project/xenia pull request #2000
Opened 2022-03-09 15:09 UTC by Margen67

```
Python 3.6 is EOL.
Use variable for Python version to make upgrading easier.
xb.bat:
 Update copyright date.
 Add candidate paths.
xb.ps1
 Properly use found python executable.
 More consistency with .bat.
 Don't spew unnecessary errors, etc.
 EOF newline.
```

2022-03-09 15:26 UTC, Triang3l commented
Which 3.7+ APIs does xenia-build use?

2022-03-09 19:49 UTC, Margen67 commented
> Which 3.7+ APIs does xenia-build require?

None, [3.6 is just EOL](https://www.python.org/downloads/release/python-3615/). If we want to keep 3.6 support I can revert it.

2022-03-09 19:54 UTC, Triang3l commented
I think unless we already specifically require something added in 3.7 or in a newer version, we shouldn't be making commits only because the maintainers of a dependency have stated that some version is out of date while still technically sufficient for us — however, Python 3.6 being deprecated by its developers means that we can more safely ignore it if it becomes maintenance burden in the future, and just drop support if we need something not available in it, or, for instance, if our Python executable search becomes overcomplicated by it.

2022-03-13 02:02 UTC, brichan commented
Don't you think that EOL increases security risks?

2022-03-13 17:00 UTC, Triang3l commented
> Don't you think that EOL increases security risks?
We don't execute any scripts from untrusted/dynamic sources, nor do we work with things involving input from the internet aside from Git submodules, there's no way our build scripts can be exploited.

2022-05-01 23:13 UTC, Miyabha commented
Dear sir plz develop the Emulator for Android xbox classic

2022-05-06 03:07 UTC, gibbed requested changes

2022-05-06 03:07 UTC, gibbed commented on xb.bat
> +SET "CANDIDATE_PATHS[2]=C:\python37\python.exe"
There's two `[2]`.

2022-05-06 06:19 UTC, illusion0001 commented on xb.bat
> +SET "CANDIDATE_PATHS[2]=C:\python37\python.exe"
```suggestion
SET "CANDIDATE_PATHS[2]=C:\python38\python.exe"
SET "CANDIDATE_PATHS[3]=C:\python37\python.exe"
SET "CANDIDATE_PATHS[4]=C:\python%PYTHON_MINIMUM_VERSION[0]%%PYTHON_MINIMUM_VERSION[1]%\python.exe"
```

2022-05-27 05:23 UTC, Margen67 commented
![](https://user-images.githubusercontent.com/3462541/170634896-76a933c1-7178-4b38-b615-9242a77c91f2.png)

2022-07-19 22:20 UTC, brichan commented
I am honestly disappointed that they are still using EOL.
The theory that if there is a security risk in EOL, it is not supported, but that is ok because we don't use it, is now a fatal security risk.

I don't understand why they can't consider the possibility that some intrusive code could search for and parasitize Python that has gone EOL.

And when that happens, the blame falls on the user, but in reality, it is the one who is condoning it.

How can developers who use Github and other internet repositories not think of that?


Translated with www.DeepL.com/Translator (free version)

2022-07-20 06:48 UTC, Triang3l commented
.bat files are even older and have way weirder and easier to break argument parsing, so should we consider them completely unsuitable for their primary purpose — local automation tasks — now? How is it suddenly a "fatal" risk in this context? While people still keep trying to use Xenia on Windows 7.

2022-07-20 08:42 UTC, JoelLinn commented
> I am honestly disappointed that they are still using EOL. 

Were exactly are _we_ using EOL Python?
 
 > but that is ok because we don't use it, is now a fatal security risk.
 
Should we blacklist msvcrt versions with known security issues?

> I don't understand why they can't consider the possibility that some intrusive code could search for and parasitize Python that has gone EOL.

We don’t consider because there is no Python _in_ this project to be found.

> And when that happens, the blame falls on the user, but in reality, it is the one who is condoning it.

I condone that someone is firing a rifle at a propane bottle that I sold them. I agree its a bad idea but I cant control how they use my propane.

> How can developers who use Github and other internet repositories not think of that?

I hope we do. But to be honest I cant see any real attack vector that we should fix. Maybe we should delete xenia because even loading a downloaded savegame is enough to get code execution I guess.

2022-07-21 13:18 UTC, brichan commented
Just to be clear, I am not talking about the Xenia execution environment.
We are talking about the Xenia build environment.
I think you know that by the purpose of this thread.

You are calling Python in xb.bat and xb.ps1.
(This is a side note, but even xb setup doesn't work with errors in the current mainstream Python 3.9.)
That's what I'm talking about there.

Your responsibility is based on Python 3.6, which is EOL and even the security fixes end at the end of 2021.
It is based on this thread's response to 3.7, which states that if you don't need the new features, you don't need to update.

It is mandatory to have Python 3.6 in the environment of Contributors and those who want to contribute to Xenia improvements, thereby posing a security risk.

2022-07-21 13:21 UTC, Margen67 commented
> 

@brichan If `xb`/`xenia-build` is broken in newer versions of Python you should create an issue about that.

2022-07-21 13:23 UTC, Triang3l commented
It is not mandatory to have Python 3.6, any version starting with 3.6 can be used, just the scripts happen to work with 3.6 too.

2022-07-21 13:31 UTC, gibbed approved these changes

2022-07-21 13:31 UTC, merged