[GPU] Allowing patch draws with less vertices then required on the host
xenia-project/xenia pull request #2007
Opened 2022-04-10 20:04 UTC by deaklajos

A patch only needs one vertex to draw on the Xenos.

2022-04-11 09:20 UTC, Triang3l requested changes

2022-04-11 09:20 UTC, Triang3l commented on src/xenia/gpu/primitive_processor.cc
> +  if (tessellation_enabled &&
For indexed draws (the R400 can tessellate regular primitives in discrete and continuous modes, not only the specialized patch primitive types), this is dangerous as indices beyond `guest_index_buffer_needed_bytes` not covered by `shared_memory_.RequestRange` will be fetched by the draw. Though I'm not sure how it should work on the real hardware in this case.

2022-04-14 18:22 UTC, Triang3l commented
Implemented in a safer location in the function (together with moving the clamping that was already there), thank you!

2022-04-14 18:22 UTC, closed without merging

2022-04-14 20:47 UTC, deaklajos commented
Thanks!